language: r
cache: packages
dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev 
  - chmod +x _build.sh

r_packages:
  - rgdal
  - sp
  - rgeos

install:
  - R -e "install.packages('devtools')"
  - R -e "devtools::install_github('nowosad/geostatbook')"

script:
  - ./_build.sh

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" 

notifications:
  email:
    on_success: change
    on_failure: change
